POST http://localhost:2002/api/auth/register
Content-Type: application/json


{
    "username": "CvKTZoesr",
    "password": "1234"
}


###
POST http://localhost:2002/api/auth/login
Content-Type: application/json


{
    "username": "CvKTZoesr",
    "password": "1234"
}

###
POST http://localhost:2002/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2YyNDI0Y2Q0OGZkMTllMDJkMTk5ZDgiLCJpYXQiOjE2NzY5MDc0MTN9.X90oeMoXXK6cAxpGBjM2A2YE73h0THD_rQJBrvjUhiQ

{
    "title": "Learning javascript",
    "description": "Learning about nodejs and framework as express",
    "url": "google.com",
    "status": ""
}

###
GET http://localhost:2002/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2YyNDI0Y2Q0OGZkMTllMDJkMTk5ZDgiLCJpYXQiOjE2Nzc3MTE2Mzl9.qs5SL1rWRlign52HlsFFpvirK_xwNDzfZinalWZUFqc
###
PUT http://localhost:2002/api/posts/63fd67e9dfdb5201ebced033
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2YyNDI0Y2Q0OGZkMTllMDJkMTk5ZDgiLCJpYXQiOjE2Nzc3MTE2Mzl9.qs5SL1rWRlign52HlsFFpvirK_xwNDzfZinalWZUFqc

{
    "title": "Learning JSX",
    "description": "Learning about nodejs and framework as express",
    "url": "google.com",
    "status": "LEARNING"
}
###
DELETE http://localhost:2002/api/posts/63f393b0b870a87005e555c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2YyNDI0Y2Q0OGZkMTllMDJkMTk5ZDgiLCJpYXQiOjE2NzgwMzMzMzB9.1wPxRgPy3Xpta4M7xAPXb7bNIZvtXqG-f-VwcD2Xl5g
